from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from ..db import get_db
from ..models import Article
from ..schemas import IngestTextReq, ArticleOut
from ..services.search_indexer import upsert_article_to_meili

router = APIRouter()

@router.post("/ingest/text", response_model=ArticleOut)
def ingest_text(req: IngestTextReq, db: Session = Depends(get_db)):
    # Check for existing article with the same URL
    if req.url:
        exists = db.query(Article).filter_by(url=req.url).first()
        if exists:
            raise HTTPException(status_code=400, detail="Article with this URL already exists")
    
    # create the ORM object(if no title, use first 60 chars of text as title)
    title = req.title or (req.text[:60] + "...")
    art = Article(
        url = req.url,
        source_platform = req.source_platform,
        title = title,
        content_text = req.text,
        tags = req.tags or [],
        summary = None  # summary to be generated by celery task
    )

    db.add(art)
    db.commit()
    db.refresh(art)
    try:
        upsert_article_to_meili(art)
    except Exception as e:
        print("meili add_documents failed:", e)
    return art